/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BlogPostInput = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const PostId = IDL.Nat;
export const ProductId = IDL.Nat;
export const CartItem = IDL.Record({
  'size' : IDL.Text,
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const OrderInput = IDL.Record({
  'customerName' : IDL.Text,
  'customerPhone' : IDL.Text,
  'totalUSD' : IDL.Float64,
  'items' : IDL.Vec(CartItem),
});
export const OrderId = IDL.Nat;
export const ProductInput = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'sizes' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'priceUSD' : IDL.Float64,
});
export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : PostId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
  'imageUrl' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'customerName' : IDL.Text,
  'status' : IDL.Text,
  'customerPhone' : IDL.Text,
  'createdAt' : Time,
  'totalUSD' : IDL.Float64,
  'items' : IDL.Vec(CartItem),
});
export const Product = IDL.Record({
  'id' : ProductId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'sizes' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'priceUSD' : IDL.Float64,
});
export const ProductUpdate = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'sizes' : IDL.Vec(IDL.Text),
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'priceUSD' : IDL.Float64,
});

export const idlService = IDL.Service({
  'createBlogPost' : IDL.Func([BlogPostInput], [PostId], []),
  'createOrder' : IDL.Func([OrderInput], [OrderId], []),
  'createProduct' : IDL.Func([ProductInput], [ProductId], []),
  'deleteBlogPost' : IDL.Func([PostId], [], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAvailableProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getBCVRate' : IDL.Func([], [IDL.Float64], ['query']),
  'getBlogPost' : IDL.Func([PostId], [BlogPost], ['query']),
  'getBlogPostsByDate' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getOrder' : IDL.Func([OrderId], [Order], ['query']),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getProductsByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'setBCVRate' : IDL.Func([IDL.Float64], [], []),
  'updateBlogPost' : IDL.Func([PostId, BlogPostInput], [BlogPost], []),
  'updateOrderStatus' : IDL.Func([OrderId, IDL.Text], [Order], []),
  'updateProduct' : IDL.Func([ProductId, ProductUpdate], [Product], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BlogPostInput = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const PostId = IDL.Nat;
  const ProductId = IDL.Nat;
  const CartItem = IDL.Record({
    'size' : IDL.Text,
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const OrderInput = IDL.Record({
    'customerName' : IDL.Text,
    'customerPhone' : IDL.Text,
    'totalUSD' : IDL.Float64,
    'items' : IDL.Vec(CartItem),
  });
  const OrderId = IDL.Nat;
  const ProductInput = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'sizes' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'priceUSD' : IDL.Float64,
  });
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : PostId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
    'imageUrl' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'customerName' : IDL.Text,
    'status' : IDL.Text,
    'customerPhone' : IDL.Text,
    'createdAt' : Time,
    'totalUSD' : IDL.Float64,
    'items' : IDL.Vec(CartItem),
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'sizes' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'priceUSD' : IDL.Float64,
  });
  const ProductUpdate = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'sizes' : IDL.Vec(IDL.Text),
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'priceUSD' : IDL.Float64,
  });
  
  return IDL.Service({
    'createBlogPost' : IDL.Func([BlogPostInput], [PostId], []),
    'createOrder' : IDL.Func([OrderInput], [OrderId], []),
    'createProduct' : IDL.Func([ProductInput], [ProductId], []),
    'deleteBlogPost' : IDL.Func([PostId], [], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAvailableProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getBCVRate' : IDL.Func([], [IDL.Float64], ['query']),
    'getBlogPost' : IDL.Func([PostId], [BlogPost], ['query']),
    'getBlogPostsByDate' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getOrder' : IDL.Func([OrderId], [Order], ['query']),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getProductsByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'setBCVRate' : IDL.Func([IDL.Float64], [], []),
    'updateBlogPost' : IDL.Func([PostId, BlogPostInput], [BlogPost], []),
    'updateOrderStatus' : IDL.Func([OrderId, IDL.Text], [Order], []),
    'updateProduct' : IDL.Func([ProductId, ProductUpdate], [Product], []),
  });
};

export const init = ({ IDL }) => { return []; };