/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : PostId,
  'title' : string,
  'content' : string,
  'date' : Time,
  'imageUrl' : string,
}
export interface BlogPostInput {
  'title' : string,
  'content' : string,
  'imageUrl' : string,
}
export interface CartItem {
  'size' : string,
  'productId' : ProductId,
  'quantity' : bigint,
}
export interface Order {
  'id' : OrderId,
  'customerName' : string,
  'status' : string,
  'customerPhone' : string,
  'createdAt' : Time,
  'totalUSD' : number,
  'items' : Array<CartItem>,
}
export type OrderId = bigint;
export interface OrderInput {
  'customerName' : string,
  'customerPhone' : string,
  'totalUSD' : number,
  'items' : Array<CartItem>,
}
export type PostId = bigint;
export interface Product {
  'id' : ProductId,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'sizes' : Array<string>,
  'imageUrl' : string,
  'category' : string,
  'priceUSD' : number,
}
export type ProductId = bigint;
export interface ProductInput {
  'name' : string,
  'description' : string,
  'available' : boolean,
  'sizes' : Array<string>,
  'imageUrl' : string,
  'category' : string,
  'priceUSD' : number,
}
export interface ProductUpdate {
  'name' : string,
  'description' : string,
  'available' : boolean,
  'sizes' : Array<string>,
  'imageUrl' : string,
  'category' : string,
  'priceUSD' : number,
}
export type Time = bigint;
export interface _SERVICE {
  'createBlogPost' : ActorMethod<[BlogPostInput], PostId>,
  'createOrder' : ActorMethod<[OrderInput], OrderId>,
  'createProduct' : ActorMethod<[ProductInput], ProductId>,
  'deleteBlogPost' : ActorMethod<[PostId], undefined>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAvailableProducts' : ActorMethod<[], Array<Product>>,
  'getBCVRate' : ActorMethod<[], number>,
  'getBlogPost' : ActorMethod<[PostId], BlogPost>,
  'getBlogPostsByDate' : ActorMethod<[], Array<BlogPost>>,
  'getOrder' : ActorMethod<[OrderId], Order>,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'getProductsByPrice' : ActorMethod<[], Array<Product>>,
  'setBCVRate' : ActorMethod<[number], undefined>,
  'updateBlogPost' : ActorMethod<[PostId, BlogPostInput], BlogPost>,
  'updateOrderStatus' : ActorMethod<[OrderId, string], Order>,
  'updateProduct' : ActorMethod<[ProductId, ProductUpdate], Product>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];